### ISSUE TITLE
Why does cargo-rpm scan for files in src/bin instead of reading the Cargo.toml spec?

### ISSUE THREAD

**Issue by stevenroose** [RustRPM/cargo-rpm#54]
Cargo.toml has these fields right?
```toml
[lib]
name = "hal"
path = "src/lib.rs"

[[bin]]
name = "hal"
path = "src/bin/hal/main.rs"
```
