### ISSUE TITLE
How to use the output with other actions 

### ISSUE THREAD

**Issue by nbari** [RustRPM/cargo-rpm#81]
Hi, first of all, many thanks for sharing this. I am trying to create an rpm and then upload it as a release from a GitHub action with something like this:

```
 build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Rust Cargo Rpm Package Build (amd64, centos8)
      id: rpm_build
      uses: nbari/cargo-rpm-amd64-centos@1.0.1

    - name: Create Release
      id: create_release
      uses: actions/create-release@latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: |
            Changes in this Release
            - Create RPM
            - Upload Source RPM
        draft: false
        prerelease: false

    - name: Upload a Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} 
        asset_path: /github/workspace/target/release/rpmbuild/RPMS/x86_64/httpwsrep-0.4.0-1.el8.x86_64.rpm
        asset_name: "httpwsrep.rpm"
        asset_content_type: "application/octet-stream"
```

The `rpm` gets created: https://github.com/nbari/httpwsrep/runs/1295799684?check_suite_focus=true#step:4:374

but then when I am trying to create the asset, I am getting a file not found: https://github.com/nbari/httpwsrep/runs/1295799684?check_suite_focus=true#step:6:10

For now, I am hardcoding the `asset_path` but wondering how could I take advantage of `cargo rpm build` and collect it so that later I could use it with something like:

    asset_path : ${{ steps.create.rpm_build.output }}

Any ideas?
